/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecretSoldenRouteImport } from './routes/secret-solden'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisitSkiRouteImport } from './routes/visit/ski'
import { Route as VisitPeopleRouteImport } from './routes/visit/people'

const SecretSoldenRoute = SecretSoldenRouteImport.update({
  id: '/secret-solden',
  path: '/secret-solden',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitSkiRoute = VisitSkiRouteImport.update({
  id: '/visit/ski',
  path: '/visit/ski',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitPeopleRoute = VisitPeopleRouteImport.update({
  id: '/visit/people',
  path: '/visit/people',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/secret-solden': typeof SecretSoldenRoute
  '/visit/people': typeof VisitPeopleRoute
  '/visit/ski': typeof VisitSkiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/secret-solden': typeof SecretSoldenRoute
  '/visit/people': typeof VisitPeopleRoute
  '/visit/ski': typeof VisitSkiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/secret-solden': typeof SecretSoldenRoute
  '/visit/people': typeof VisitPeopleRoute
  '/visit/ski': typeof VisitSkiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/secret-solden' | '/visit/people' | '/visit/ski'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/secret-solden' | '/visit/people' | '/visit/ski'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/secret-solden'
    | '/visit/people'
    | '/visit/ski'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SecretSoldenRoute: typeof SecretSoldenRoute
  VisitPeopleRoute: typeof VisitPeopleRoute
  VisitSkiRoute: typeof VisitSkiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/secret-solden': {
      id: '/secret-solden'
      path: '/secret-solden'
      fullPath: '/secret-solden'
      preLoaderRoute: typeof SecretSoldenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit/ski': {
      id: '/visit/ski'
      path: '/visit/ski'
      fullPath: '/visit/ski'
      preLoaderRoute: typeof VisitSkiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit/people': {
      id: '/visit/people'
      path: '/visit/people'
      fullPath: '/visit/people'
      preLoaderRoute: typeof VisitPeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SecretSoldenRoute: SecretSoldenRoute,
  VisitPeopleRoute: VisitPeopleRoute,
  VisitSkiRoute: VisitSkiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
